"""
antar_engine/ask_consultation.py
=================================
Consultation layer for /api/v1/ask — launch sprint 2026-06-03.

Gives /ask the three-part consultation answer on real, deterministic inputs:
  1. VERDICT + TIMING — from a 2-of-3 convergence across Vimshottari (MD/AD),
     Chara dasha, and Varshphal. Python computes the window; Claude narrates.
  2. ACTIONS — generated by Claude FROM the convergence facts (never invented
     dates — the window is pinned in the prompt).
  3. PRACTICES — markable PracticeCards come from the existing practice
     engine (practice_id linkage to practice_log), assembled in main.py.

Shared primitives with /predict: dasha_periods rows (get_dashas_for_chart
shape), varshaphal_table.get_annual_house, detect_concern domain names.
No LLM calls in this module. No prose duplication of /predict's context.
"""

from __future__ import annotations

from datetime import date, timedelta
from typing import Optional

SIGNS = ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra",
         "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"]

SIGN_LORDS = {
    "Aries": "Mars", "Taurus": "Venus", "Gemini": "Mercury", "Cancer": "Moon",
    "Leo": "Sun", "Virgo": "Mercury", "Libra": "Venus", "Scorpio": "Mars",
    "Sagittarius": "Jupiter", "Capricorn": "Saturn", "Aquarius": "Saturn",
    "Pisces": "Jupiter",
}

# concern (detect_concern names) -> target houses.
# Aligned with /predict's relevant_divisions and prashna DOMAIN_HOUSE_MAP:
# funding/finance = 2nd (cash) + 8th (other people's money) + 11th (gains).
CONCERN_HOUSES = {
    "finance":     [2, 8, 11],
    "funding":     [8, 11, 2],
    "wealth":      [2, 11],
    "loss":        [8, 12, 2],
    "speculation": [5, 2, 11],
    "career":      [10, 6, 11],
    "business":    [7, 10, 11],
    "marriage":    [7],
    "love":        [5, 7],
    "divorce":     [7, 6],
    # [evmap-2026-06-07] domestic vs foreign distinction
    "domestic_move": [4, 3, 11],
    "foreign_move":  [12, 9, 3],
    # [routing-2026-06-07] reconciliation: 7 (partnership), 5 (romance/heart),
    # 4 (emotional foundation / re-building). Distinct from divorce (which
    # looks for separation triggers) — this looks for re-binding signals.
    "reconciliation": [7, 5, 4],
    "health":      [6, 1, 8],
    "foreign":     [12, 9],
    "children":    [5],
    "property":    [4, 2],
    "education":   [5, 9],
    "legal":       [6, 7],
    "spiritual":   [9, 12],
    "general":     [10, 11],
}

# Natural karaka planets per concern — used by the Varshphal lock.
CONCERN_KARAKAS = {
    "finance":     ["Jupiter", "Venus", "Mercury"],
    "funding":     ["Jupiter", "Venus", "Mercury", "Rahu"],
    "wealth":      ["Jupiter", "Venus"],
    "speculation": ["Mercury", "Rahu"],
    "career":      ["Sun", "Saturn", "Mars", "Mercury"],
    "business":    ["Mercury", "Jupiter"],
    "marriage":    ["Venus", "Jupiter"],
    "love":        ["Venus", "Moon"],
    # [evmap-2026-06-07] domestic move = Mars+Moon (action+home), foreign = Rahu+Jupiter
    "domestic_move": ["Mars", "Moon", "Venus"],
    "foreign_move":  ["Rahu", "Jupiter", "Moon"],
    # [routing-2026-06-07] reconciliation karakas — Venus (love/repair),
    # Moon (emotional re-bonding), Jupiter (wisdom/forgiveness).
    "reconciliation": ["Venus", "Moon", "Jupiter"],
    "health":      ["Sun", "Mars"],
    "foreign":     ["Rahu", "Moon"],
    "children":    ["Jupiter"],
    "property":    ["Mars", "Venus"],
    "education":   ["Mercury", "Jupiter"],
    "legal":       ["Jupiter", "Saturn"],
    "spiritual":   ["Ketu", "Jupiter"],
}

# Decision/timing question patterns — EN + ES (live app runs Spanish too).
# Anything in this list routes to build_convergence_timing → real verdict.
# Anything NOT in this list takes the reflective fallback path (no verdict).
# Expanded 2026-06-07 to cover chance/odds/possibility/reunion phrasings the
# audit showed were silently falling through ("is there a chance of reuniting…").
_DECISION_TRIGGERS = [
    # English — direct timing
    "when ", "when?", "by when", "how soon", "how long until",
    "what month", "what year", "which month", "which quarter",
    # English — will/should/can framings
    "will i", "will my", "will we", "will this", "will the", "will it",
    "should i", "should we", "can i ", "could i",
    "do i get", "am i going to",
    # English — good-time framings
    "is it a good time", "right time", "good time to",
    # English — chance / odds / possibility (covers Failure 2)
    "is there a chance", "any chance", "chance of",
    "what are the chances", "what's the chance", "whats the chance",
    "what are my odds", "odds of", "likelihood of", "possibility of",
    "is there hope", "any hope of", "is it possible", "could there be",
    "could we", "could it", "could it be",
    # English — relationship-reunion specific (covers Failure 2 directly)
    "are we getting back", "get back together", "getting back together",
    "back together", "reunite", "reuniting", "reunion",
    "rekindle", "rekindling", "second chance",
    "fix things with", "work things out", "fix it with",
    # English — career / business specific timing intent
    "do i land", "will i land", "what are the chances of landing",
    # Spanish — direct timing
    "cuándo", "cuando ", "conseguiré", "lograré", "obtendré", "recibiré",
    "tendré", "podré",
    "voy a conseguir", "voy a lograr", "voy a recibir",
    "debo ", "debería",
    "es buen momento", "buen momento para",
    "en qué mes", "en que mes", "qué año", "que año",
    # Spanish — chance / odds / possibility
    "hay una posibilidad", "alguna posibilidad", "hay alguna chance",
    "qué probabilidad", "que probabilidad", "qué chance", "que chance",
    "tendré otra oportunidad", "habrá oportunidad",
    "es posible", "es posible que",
    # Spanish — reconciliation
    "volveremos", "reconciliarnos", "reconciliar", "volver con",
    "volver juntos", "rehacer la relación", "una segunda oportunidad",
]


# detect_concern names that the pre-scan's DOMAIN_VOCABULARY / house map
# don't recognize — alias them so no classified question silently falls
# back to DOMAIN: GENERAL (acceptance-test criterion).
PRESCAN_DOMAIN_ALIAS = {
    "love": "relationship", "marriage": "relationship", "divorce": "relationship",
    "reconciliation": "relationship",  # [routing-2026-06-07] reunion questions
    # [evmap-2026-06-07] both relocation flavours pre-scan as "property"
    # (the pre-scan vocabulary that already knows 4H + 12H rules).
    "domestic_move": "property", "foreign_move": "foreign",
    "funding": "finance", "loss": "finance", "speculation": "finance",
    "money": "finance", "billionaire": "wealth", "rich": "wealth",
    "spiritual": "general",
}


def prescan_domain(concern: str) -> str:
    """Map a detect_concern result to a domain the pre-scan understands."""
    return PRESCAN_DOMAIN_ALIAS.get(concern, concern or "general")


def is_decision_question(question: str) -> bool:
    """True if the question wants a verdict and/or a timing window."""
    q = " " + (question or "").lower().strip() + " "
    if q.strip().startswith(("when", "cuándo", "cuando")):
        return True
    return any(t in q for t in _DECISION_TRIGGERS)


# ───────────────────────── row helpers (dasha_periods shape) ─────────────

def _parse_d(s) -> Optional[date]:
    try:
        return date.fromisoformat(str(s)[:10])
    except Exception:
        return None


def _rows(dashas, system):
    return (dashas or {}).get(system, []) or []


def _level(r) -> str:
    return str(r.get("level") or r.get("type", "")).lower()


def _lord(r) -> str:
    return r.get("lord_or_sign") or r.get("planet_or_sign", "")


def _win(r):
    return (_parse_d(r.get("start_date") or r.get("start")),
            _parse_d(r.get("end_date") or r.get("end")))


def _lagna_idx(chart_data) -> int:
    lagna = (chart_data or {}).get("lagna", {})
    if isinstance(lagna, dict):
        si = lagna.get("sign_index")
        if isinstance(si, int) and 0 <= si <= 11:
            return si
        name = lagna.get("sign", "")
    else:
        name = str(lagna)
    return SIGNS.index(name) if name in SIGNS else 0


def _house_lords(lagna_idx) -> dict:
    """Whole-sign house lords computed from the lagna — independent of the
    (string-keyed) chart_data.house_lords column."""
    return {h: SIGN_LORDS[SIGNS[(lagna_idx + h - 1) % 12]] for h in range(1, 13)}


def _fmt_window(s: Optional[date], e: Optional[date]) -> str:
    if not s or not e:
        return ""
    # Same-month window: "Jun 2026 – Jun 2026" reads broken — collapse.
    if (s.year, s.month) == (e.year, e.month):
        return s.strftime("%b %Y")
    return f"{s.strftime('%b %Y')} – {e.strftime('%b %Y')}"


# ───────────────────────── per-system locks ──────────────────────────────

def _current_dasha_lords(dashas, today):
    """[slice-1b] Running Vimshottari MD + AD lords for the promise engine."""
    md = ad = ""
    for r in _rows(dashas, "vimsottari"):
        lv = _level(r)
        s, e = _win(r)
        if not (s and e and s <= today <= e):
            continue
        if lv in ("mahadasha", "1") and not md:
            md = _lord(r)
        elif lv in ("antardasha", "antar", "2") and not ad:
            ad = _lord(r)
    return md, ad


def _vimshottari_lock(dashas, chart_data, houses, lords, today, horizon):
    """Earliest current/upcoming Vimshottari period whose lord rules or
    occupies a target house. AD windows preferred (tighter)."""
    planets = (chart_data or {}).get("planets") or {}

    def qualifies(p):
        if not p:
            return False
        if p in lords:
            return True
        return (planets.get(p) or {}).get("house") in houses

    best = None
    for want_ad in (True, False):
        for r in _rows(dashas, "vimsottari"):
            lv = _level(r)
            is_ad = lv in ("antardasha", "antar", "2")
            is_md = lv in ("mahadasha", "1")
            if want_ad and not is_ad:
                continue
            if not want_ad and not is_md:
                continue
            s, e = _win(r)
            if not s or not e or e < today or s > horizon:
                continue
            p = _lord(r)
            if qualifies(p):
                cs, ce = max(s, today), min(e, horizon)
                if best is None or cs < best[1]:
                    kind = "sub-chapter" if is_ad else "chapter"
                    role = "rules" if p in lords else "occupies"
                    best = (p, cs, ce, f"{p} {kind} {role} a target area, {_fmt_window(cs, ce)}")
        if best:
            break
    if best:
        return {"active": True, "start": best[1], "end": best[2], "why": best[3], "planet": best[0]}
    return {"active": False, "start": None, "end": None, "why": "no period lord touches the target areas in the horizon", "planet": ""}


def _next_vim_window(dashas, chart_data, houses, lords, after, horizon):
    """Earliest qualifying Vimshottari window STARTING after `after` —
    surfaces the next opening when the current window is the tail of an
    ending chapter (e.g. funding: Mars MD ends Aug 2026, Rahu in the gains
    area takes over)."""
    planets = (chart_data or {}).get("planets") or {}

    def qualifies(p):
        if not p:
            return False
        if p in lords:
            return True
        return (planets.get(p) or {}).get("house") in houses

    best = None
    for r in _rows(dashas, "vimsottari"):
        lv = _level(r)
        if lv not in ("antardasha", "antar", "2", "mahadasha", "1"):
            continue
        s, e = _win(r)
        # s >= after keeps same-day chapter handoffs (e.g. Mars ends Aug 13,
        # Rahu starts Aug 13) — but skip rows already underway before `after`
        if not s or not e or s < after or s > horizon:
            continue
        p = _lord(r)
        if qualifies(p) and (best is None or s < best[1]):
            kind = "sub-chapter" if lv in ("antardasha", "antar", "2") else "chapter"
            role = "rules" if p in lords else "occupies"
            best = (p, s, min(e, horizon), f"{p} {kind} ({role} a target area) opens {s.strftime('%b %Y')}")
    if best:
        return {"planet": best[0], "start": best[1], "end": best[2],
                "label": _fmt_window(best[1], best[2]), "why": best[3]}
    return None


def _yogini_lock(dashas, chart_data, houses, lords, today, horizon):
    """[unify 2026-07-26] Earliest current/upcoming Yoginī period whose lord
    rules or occupies a target house — a fourth confirming clock. Planet-based,
    so it mirrors _vimshottari_lock exactly (Yoginī stores a graha lord, not a
    sign). AD windows preferred."""
    planets = (chart_data or {}).get("planets") or {}

    def qualifies(p):
        if not p:
            return False
        if p in lords:
            return True
        return (planets.get(p) or {}).get("house") in houses

    best = None
    for want_ad in (True, False):
        for r in _rows(dashas, "yogini"):
            lv = _level(r)
            is_ad = lv in ("antardasha", "antar", "2")
            is_md = lv in ("mahadasha", "1")
            if want_ad and not is_ad:
                continue
            if not want_ad and not is_md:
                continue
            s, e = _win(r)
            if not s or not e or e < today or s > horizon:
                continue
            p = _lord(r)
            if qualifies(p):
                cs, ce = max(s, today), min(e, horizon)
                if best is None or cs < best[1]:
                    kind = "sub-period" if is_ad else "period"
                    role = "rules" if p in lords else "occupies"
                    best = (p, cs, ce, f"{p} {kind} {role} a target area, {_fmt_window(cs, ce)}")
        if best:
            break
    if best:
        return {"active": True, "start": best[1], "end": best[2], "why": best[3], "planet": best[0]}
    return {"active": False, "start": None, "end": None,
            "why": "no Yogini period touches the target areas in the horizon", "planet": ""}


def _chara_lock(dashas, lagna_idx, houses, lords, today, horizon):
    """Earliest current/upcoming Chara sign period that activates a target
    house (sign sits in a target house from lagna, or sign's lord is a
    target-house lord). AD sign periods preferred."""
    best = None
    for want_ad in (True, False):
        for r in _rows(dashas, "jaimini"):
            lv = _level(r)
            is_ad = lv in ("antardasha", "antar", "2")
            is_md = lv in ("mahadasha", "1")
            if want_ad and not is_ad:
                continue
            if not want_ad and not is_md:
                continue
            sign = _lord(r)
            if sign not in SIGNS:
                continue
            s, e = _win(r)
            if not s or not e or e < today or s > horizon:
                continue
            sign_house = (SIGNS.index(sign) - lagna_idx) % 12 + 1
            _by_house = sign_house in houses
            _by_lord = SIGN_LORDS[sign] in lords
            if _by_house or _by_lord:
                cs, ce = max(s, today), min(e, horizon)
                if best is None or cs < best[1]:
                    kind = "sub-period" if is_ad else "period"
                    if _by_house:
                        reason = f"sits in target house {sign_house}"
                    else:
                        reason = f"its lord {SIGN_LORDS[sign]} rules a target area"
                    best = (sign, cs, ce,
                            f"{sign} {kind} {reason}, {_fmt_window(cs, ce)}")
        if best:
            break
    if best:
        return {"active": True, "start": best[1], "end": best[2], "why": best[3],
                "planet": SIGN_LORDS.get(best[0], "")}
    return {"active": False, "start": None, "end": None, "why": "no sign period activates the target areas in the horizon", "planet": ""}


def _varshphal_lock(chart_data, birth_date, houses, lords, karakas, today):
    """Does this Varshphal year send a domain-relevant planet (target-house
    lord or natural karaka) into a target annual house? Window = the annual
    chart's validity (birthday to birthday). Same get_annual_house as /predict."""
    born = _parse_d(birth_date)
    if not born:
        return {"active": False, "start": None, "end": None, "why": "birth date unavailable"}
    try:
        from antar_engine.varshaphal_table import get_annual_house
    except Exception:
        return {"active": False, "start": None, "end": None, "why": "varshphal table unavailable"}

    age = (today - born).days // 365
    try:
        last_bday = born.replace(year=today.year)
    except ValueError:  # Feb 29
        last_bday = born.replace(year=today.year, day=28)
    if last_bday > today:
        last_bday = last_bday.replace(year=last_bday.year - 1)
    next_bday = last_bday.replace(year=last_bday.year + 1)

    relevant = set(lords) | set(karakas)
    hits, hit_planets = [], []
    for p, d in ((chart_data or {}).get("planets") or {}).items():
        nh = d.get("house") if isinstance(d, dict) else None
        if nh and 1 <= nh <= 12 and p in relevant:
            ah = get_annual_house(nh, age)
            if ah in houses:
                hits.append(f"{p} lands in annual house {ah}")
                hit_planets.append(p)
    if hits:
        return {"active": True, "start": last_bday, "end": next_bday,
                "why": "; ".join(hits[:3]) + f", valid {_fmt_window(last_bday, next_bday)}",
                "planet": hit_planets[0]}
    return {"active": False, "start": last_bday, "end": next_bday,
            "why": "this year's chart does not move relevant planets into the target areas",
            "planet": ""}


# ───────────────────────── convergence (2-of-3) ──────────────────────────

# [unify 2026-07-26] Draw the timing weights from the ONE shared module
# (prediction_weights) so Ask and the life-arc ECS can no longer drift, and add
# Yoginī as a fourth system. Vimśottarī stays the reference and the bar equals
# its weight, so the tuned behaviour is preserved: a lone Vimśottarī lock still
# crosses; Chara / Yoginī / Varshphal alone do not. Yoginī sits at 0.75 (below
# Chara's 0.90) because it shares Vimśottarī's nakshatra basis — the same
# independence ranking the module encodes.
try:
    from antar_engine.prediction_weights import DEFAULT_WEIGHTS as _PW
    _SYS_WEIGHT = {
        "vimshottari": _PW["vimshottari_maha"],
        "chara":       _PW["jaimini_chara_maha"],
        "yogini":      _PW["yogini_maha"],
        "varshphal":   _PW.get("varshphal", 0.65),
        "transit":     _PW["transit_double"],
    }
    _CONVERGENCE_BAR = _PW["vimshottari_maha"]
except Exception:
    # Fail-safe: never let a weights-import issue break the Ask timing path.
    _SYS_WEIGHT = {"vimshottari": 1.0, "chara": 0.90, "yogini": 0.75,
                   "varshphal": 0.65, "transit": 0.85}
    _CONVERGENCE_BAR = 1.0


def _month_end(d):
    nxt = date(d.year + 1, 1, 1) if d.month == 12 else date(d.year, d.month + 1, 1)
    return nxt - timedelta(days=1)


def _month_starts(start, end):
    out, y, m = [], start.year, start.month
    while (y, m) <= (end.year, end.month):
        out.append(date(y, m, 1))
        m += 1
        if m > 12:
            m = 1; y += 1
    return out


def _vimshottari_windows(dashas, chart_data, houses, lords, today, horizon):
    """[slice-4c] ALL qualifying Vimshottari windows in the horizon (not just the
    earliest) so net(t) can weigh multiple openings. Prefers the tight AD windows
    (possibly several); falls back to the broad MD window only if no AD qualifies,
    mirroring _vimshottari_lock's AD preference. A window qualifies when its lord
    rules or occupies a target house."""
    planets = (chart_data or {}).get("planets") or {}

    def _q(p):
        return bool(p) and (p in lords or (planets.get(p) or {}).get("house") in houses)

    ad, md = [], []
    for r in _rows(dashas, "vimsottari"):
        lv = _level(r)
        is_ad = lv in ("antardasha", "antar", "2")
        is_md = lv in ("mahadasha", "1")
        if not (is_ad or is_md):
            continue
        s, e = _win(r)
        if not s or not e or e < today or s > horizon:
            continue
        if _q(_lord(r)):
            (ad if is_ad else md).append((max(s, today), min(e, horizon)))
    return ad if ad else md


def _weighted_convergence_timeline(sys_windows, today, horizon):
    """[slice-4c] net(t) over monthly buckets from PER-SYSTEM window lists. A
    system adds its weight to a month if ANY of its windows covers it (no
    within-system double count). The earliest at/above-bar run is the primary
    window; later runs are returned as secondary peaks. Returns
    (timing_score, convergence_met, window_start, window_end, secondary_windows),
    timing_score = the PRIMARY run's peak; secondary_windows = [{label, score}]."""
    months = _month_starts(today, horizon)
    if not months:
        return 0.0, False, None, None, []
    net = []
    for mo in months:
        mend = _month_end(mo)
        w = 0.0
        for sysname, wins in sys_windows.items():
            if any(s and e and s <= mend and e >= mo for (s, e) in (wins or [])):
                w += _SYS_WEIGHT.get(sysname, 1.0)
        net.append(round(w, 2))
    if max(net) < _CONVERGENCE_BAR:
        return round(max(net), 2), False, None, None, []
    runs, i = [], 0
    while i < len(net):
        if net[i] >= _CONVERGENCE_BAR:
            j = i
            while j + 1 < len(net) and net[j + 1] >= _CONVERGENCE_BAR:
                j += 1
            runs.append((i, j, max(net[i:j + 1])))
            i = j + 1
        else:
            i += 1
    peak = max(net)                                 # primary = the strongest,
    pk = net.index(peak)                            # peak-level sub-window
    prun = next(r for r in runs if r[0] <= pk <= r[1])
    lo = hi = pk
    while lo - 1 >= prun[0] and net[lo - 1] == peak:
        lo -= 1
    while hi + 1 <= prun[1] and net[hi + 1] == peak:
        hi += 1
    ws = max(months[lo], today)
    we = min(_month_end(months[hi]), horizon)
    secondary = [{"label": _fmt_window(max(months[a], today),
                                       min(_month_end(months[b]), horizon)),
                  "score": rp} for (a, b, rp) in runs if not (a <= pk <= b)]
    return round(peak, 2), True, ws, we, secondary


def _transit_windows(concern, chart_data, houses, lagna_idx, today, horizon):
    """[unify 2026-07-26] Double-transit (Jupiter AND Saturn influencing the
    concern's target signs) windows inside the horizon — the gochara TRIGGER,
    returned as (start,end) date tuples so it plugs into the same convergence
    timeline as the dasha locks. Reuses the cached transit_engine chronology;
    returns [] on any issue (fail-open)."""
    try:
        from antar_engine import transit_engine as _te
        from datetime import datetime as _dt
        moon_si = _planet_sign_idx_local(chart_data, "Moon")
        tgt = _te.event_transit_targets(
            event_houses=list(houses), lagna_sign_index=lagna_idx,
            moon_sign_index=moon_si)
        targets = tgt.get("targets")
        if not targets:
            return []
        start_iso, end_iso = today.isoformat(), horizon.isoformat()
        chron = _te.build_transit_chronology(start_iso, end_iso,
                                             ("Jupiter", "Saturn"), step_days=5)
        wins = _te.double_transit_windows(targets, chron, start_iso, end_iso)
        out = []
        for w in wins:
            try:
                s = _dt.fromisoformat(w["start"][:10]).date()
                e = _dt.fromisoformat(w["end"][:10]).date()
                out.append((s, e))
            except Exception:
                continue
        return out
    except Exception:
        return []


def _planet_sign_idx_local(chart_data, planet):
    p = ((chart_data or {}).get("planets") or {}).get(planet) or {}
    si = p.get("sign_index")
    if isinstance(si, int):
        return si % 12
    nm = p.get("sign")
    return SIGNS.index(nm) if nm in SIGNS else None


# [unify 2026-07-26] D9/D10 confirmation for Ask — does the divisional back the
# rāśi timing? Career-type concerns judged in D10, relationship/family in D9.
_VARGA_EXALT = {"Sun": "Aries", "Moon": "Taurus", "Mars": "Capricorn",
                "Mercury": "Virgo", "Jupiter": "Cancer", "Venus": "Pisces",
                "Saturn": "Libra"}
_VARGA_DEBIL = {"Sun": "Libra", "Moon": "Scorpio", "Mars": "Cancer",
                "Mercury": "Pisces", "Jupiter": "Capricorn", "Venus": "Virgo",
                "Saturn": "Aries"}
_CONCERN_VARGA = {
    "career": "d10", "business": "d10", "finance": "d10", "funding": "d10",
    "wealth": "d10", "job": "d10", "promotion": "d10",
    "marriage": "d9", "love": "d9", "relationship": "d9", "divorce": "d9",
    "reconciliation": "d9", "children": "d9", "family": "d9",
}


def _varga_confirm(concern, chart_data, planet):
    """{status, mult, note} — the period lord's dignity in the concern's varga.
    status ∈ confirmed | denied | neutral. Mirrors the life-arc Varga_mult so
    Ask and the cycle read the divisional the same way. Nodes/absent → neutral."""
    vk = _CONCERN_VARGA.get((concern or "").lower())
    if not vk or planet in ("Rahu", "Ketu", "", None):
        return {"status": "neutral", "mult": 1.0, "note": ""}
    dv = (chart_data.get("divisional_charts") or {}).get(vk) or {}
    vp = (dv.get("planets") or {}).get(planet) or {}
    vsign = vp.get("sign")
    if vsign not in SIGNS:
        return {"status": "neutral", "mult": 1.0, "note": ""}
    d1 = (chart_data.get("planets") or {}).get(planet) or {}
    d1sign = d1.get("sign")
    varga_name = "career chart" if vk == "d10" else "relationship chart"
    if (d1sign and vsign == d1sign) or vsign == _VARGA_EXALT.get(planet):
        return {"status": "confirmed", "mult": 1.15,
                "note": f"the {varga_name} strongly backs this"}
    if SIGN_LORDS.get(vsign) == planet:
        return {"status": "confirmed", "mult": 1.10,
                "note": f"the {varga_name} supports this"}
    if vsign == _VARGA_DEBIL.get(planet):
        return {"status": "denied", "mult": 0.40,
                "note": f"the {varga_name} weakens this — the promise is thinner than it looks"}
    return {"status": "neutral", "mult": 1.0, "note": ""}


def build_convergence_timing(concern, chart_data, dashas, birth_date,
                             horizon_months: int = 24) -> dict:
    """
    Deterministic WEIGHTED convergence across Vimshottari + Chara + Varshphal
    [slice-4]: each system carries a weight and convergence is a continuous
    timing_score crossing a bar — a lone strong system qualifies, no 2-of-3
    cliff. Returns lock states, lock_count, timing_score, convergence_met, and
    a timing window (overlap of the agreeing systems' windows, clipped to the
    horizon).
    """
    today = date.today()
    horizon = today + timedelta(days=horizon_months * 30)
    houses = CONCERN_HOUSES.get(concern, CONCERN_HOUSES["general"])
    karakas = CONCERN_KARAKAS.get(concern, ["Jupiter", "Sun"])
    lagna_idx = _lagna_idx(chart_data)
    lords = {_house_lords(lagna_idx)[h] for h in houses}

    locks = {
        "vimshottari": _vimshottari_lock(dashas, chart_data, houses, lords, today, horizon),
        "chara":       _chara_lock(dashas, lagna_idx, houses, lords, today, horizon),
        "yogini":      _yogini_lock(dashas, chart_data, houses, lords, today, horizon),
        "varshphal":   _varshphal_lock(chart_data, birth_date, houses, lords, karakas, today),
    }
    # [slice-4b] net(t) weighted convergence over monthly buckets — scores
    # actual TEMPORAL overlap (non-overlapping systems never falsely stack).
    lock_count = sum(1 for v in locks.values() if v["active"])  # kept for compat
    _vim_wins = _vimshottari_windows(dashas, chart_data, houses, lords, today, horizon)
    _sys_windows = {"vimshottari": _vim_wins}
    for _sk in ("chara", "yogini", "varshphal"):
        _slk = locks.get(_sk, {})
        if _slk.get("active") and _slk.get("start") and _slk.get("end"):
            _sys_windows[_sk] = [(_slk["start"], _slk["end"])]
    # [unify 2026-07-26] Gochara as a fifth window-system — the Rao double-transit
    # over the concern's target signs. It fits the same window-overlap model the
    # dasha locks use (it produces (start,end) intervals), so it participates in
    # convergence directly rather than as a bolt-on. Fail-open: any transit issue
    # just omits the system, never breaks the timing.
    try:
        _tr_wins = _transit_windows(concern, chart_data, houses, lagna_idx, today, horizon)
        if _tr_wins:
            _sys_windows["transit"] = _tr_wins
    except Exception as _tr_e:
        print(f"[ask-timing] transit windows skipped (non-fatal): {_tr_e}")
    timing_score, convergence_met, _tl_ws, _tl_we, _tl_secondary = \
        _weighted_convergence_timeline(_sys_windows, today, horizon)

    # Domain-relevant planets — active lock planets first, then target-house
    # lords, then natural karakas. Used to pick domain-matched practices.
    relevant_planets = []
    for v in locks.values():
        p = v.get("planet")
        if p and p not in relevant_planets:
            relevant_planets.append(p)
    for p in list(lords) + list(karakas):
        if p and p not in relevant_planets:
            relevant_planets.append(p)

    # [slice-4b] window = the net(t) peak run (real temporal agreement).
    window_start, window_end = _tl_ws, _tl_we

    # Next opening after the current window (or after today if none) — e.g.
    # funding: Mars chapter tail ends Aug 2026, Rahu opens the gains area next.
    next_win = _next_vim_window(dashas, chart_data, houses, lords,
                                window_end or today, horizon)

    window_label = _fmt_window(window_start, window_end)
    if convergence_met and window_label:
        if lock_count >= 2:
            summary = f"{lock_count} of 3 timing systems converge (score {timing_score}): window {window_label}"
            public_summary = f"{lock_count} of 3 timing systems point to {window_label}"
        else:
            _only = next((k for k, v in locks.items() if v.get("active")), "primary")
            summary = f"primary timing system active ({_only}, score {timing_score}): window {window_label}"
            public_summary = f"the main timing system points to {window_label}"
    elif lock_count >= 1:
        _only = next((k for k, v in locks.items() if v.get("active")), "one")
        summary = f"1 of 3 systems active ({_only}, score {timing_score}) — below convergence; building phase"
        public_summary = "1 timing system active — building phase, no strong window yet"
    else:
        summary = "0 of 3 systems active — no supportive window inside the horizon"
        public_summary = "No strong timing window in the next 24 months — building phase"

    _conv_for_verdict = {
        "lock_count": lock_count,
        "convergence_met": convergence_met,
        "window_start": window_start.isoformat() if window_start else None,
        "window_end": window_end.isoformat() if window_end else None,
        "next_window_label": (next_win or {}).get("label"),
    }
    _verdict, _verdict_phrase = _derive_verdict_phrase(
        _conv_for_verdict, concern, date.today())

    # ── Stage 1: PROMISE + earned confidence + agency dial [ask-promise] ──
    # Fail-open: assess_promise never raises; promise=None => unchanged output.
    try:
        from antar_engine.ask_promise import assess_promise
        _md_l, _ad_l = _current_dasha_lords(dashas, today)
        _prom = assess_promise(chart_data, houses, karakas,
                               md_lord=_md_l, ad_lord=_ad_l, concern=concern)
    except Exception:
        _prom = {"promise": None, "band": None, "agency_weight": None, "factors": []}
    _pband = _prom.get("band")
    # [slice-4] continuous timing strength: shape the band by whether the
    # window is open now / future / absent, then scale within it by the score.
    _ts_norm = min(1.0, timing_score / 2.9)   # 2.9 = all three systems active
    if convergence_met and window_start and window_end and window_start <= today <= window_end:
        _t_scalar = round(0.75 + 0.25 * _ts_norm, 3)
    elif convergence_met and window_start and window_start > today:
        _t_scalar = round(0.55 + 0.25 * _ts_norm, 3)
    elif lock_count >= 1:
        _t_scalar = round(0.25 + 0.15 * _ts_norm, 3)
    else:
        _t_scalar = 0.15
    _confidence = (round(_prom["promise"] * _t_scalar, 2)
                   if _prom.get("promise") is not None else None)
    # Over-claim guard: strong timing, weak/absent promise -> soften the
    # opening (enum unchanged) and let the answer lean toward agency.
    if _pband in ("weak", "absent") and _verdict in ("SUPPORTED", "LIKELY"):
        _verdict_phrase = _soften_ask_phrase(
            concern, _pband, window_label or (next_win or {}).get("label"))
        _verdict = promise_adjusted_verdict(_verdict, _pband)
    # [unify 2026-07-26] D9/D10 confirmation on the primary (Vimshottari) lock
    # planet — the same divisional check the life-arc ECS runs. Additive: exposed
    # for the narration/verdict layer; does not alter the window math.
    _varga = _varga_confirm(concern, chart_data,
                            (locks.get("vimshottari") or {}).get("planet", ""))

    return {
        "concern": concern,
        "houses": houses,
        "locks": {k: {"active": v["active"], "why": v["why"],
                      "window": _fmt_window(v["start"], v["end"])}
                  for k, v in locks.items()},
        "varga_confirm": _varga,
        "lock_count": lock_count,
        "convergence_met": convergence_met,
        "window_start": window_start.isoformat() if window_start else None,
        "window_end": window_end.isoformat() if window_end else None,
        "window_label": window_label or None,
        "timing_score": timing_score,
        "secondary_windows": _tl_secondary,
        "next_window_label": (next_win or {}).get("label"),
        "next_window_why": (next_win or {}).get("why"),
        "relevant_planets": relevant_planets,
        "summary": summary,
        "public_summary": public_summary,
        "verdict":        _verdict,         # [lead-verdict]
        "verdict_phrase": _verdict_phrase,  # [lead-verdict]
        # [ask-promise] Stage-1 evidence + earned confidence + agency dial.
        "promise":         _prom.get("promise"),
        "promise_band":    _pband,
        "promise_factors": _prom.get("factors"),
        "agency_weight":   _prom.get("agency_weight"),
        "confidence":      _confidence,
    }


# Domain-specific noun for the deterministic opening sentence ("funding window",
# "partnership window", "career opening"). Keep nouns SHORT and concrete — the
# whole point is to drop vague energy-talk and lead with a real-noun + date.
_DOMAIN_NOUN = {
    "finance":     "funding window",
    "funding":     "funding window",
    "wealth":      "money window",
    "loss":        "financial window",
    "speculation": "speculative window",
    "career":      "career window",
    "business":    "business window",
    "marriage":    "partnership window",
    "love":        "partnership window",
    "divorce":     "partnership transition",
    "reconciliation": "reconnection window",
    "children":    "family window",
    "domestic_move": "domestic move window",
    "foreign_move":  "foreign move window",
    "health":      "health window",
    "foreign":     "relocation window",
    "children":    "family window",
    "property":    "property window",
    "education":   "education window",
    "legal":       "legal window",
    "spiritual":   "spiritual window",
    "general":     "opening",
}


def _derive_verdict_phrase(conv: dict, concern: str, today: date) -> tuple:
    """
    Python-authoritative opening sentence for /ask. Returns (verdict_enum,
    verdict_phrase) where:
      verdict_enum   ∈ {SUPPORTED, LIKELY, NOT_THIS_YEAR, NOT_YET, NO}
      verdict_phrase = exact sentence the narrator's `read` must open with.

    The phrase is deterministic — built from the engine's lock_count, window
    bounds, and the domain noun. Never invents dates; only restates what the
    convergence engine produced.
    """
    noun = _DOMAIN_NOUN.get(concern, "opening")
    lock_count      = int(conv.get("lock_count") or 0)
    convergence_met = bool(conv.get("convergence_met"))
    ws_str          = conv.get("window_start")
    we_str          = conv.get("window_end")
    next_label      = conv.get("next_window_label") or ""

    try:
        ws = date.fromisoformat(ws_str) if ws_str else None
    except Exception:
        ws = None
    try:
        we = date.fromisoformat(we_str) if we_str else None
    except Exception:
        we = None

    # ── Convergence + window — the strong answers ────────────────────────
    if convergence_met and ws and we:
        if ws <= today <= we:
            month_end = we.strftime("%B %Y")
            return "SUPPORTED", f"Yes — {noun} is open now, through {month_end}."
        if ws > today:
            month_start = ws.strftime("%B %Y")
            month_end   = we.strftime("%B %Y")
            # Same calendar year as today → "this year, through {month_end}"
            if ws.year == today.year and we.year == today.year:
                return "LIKELY", f"Likely, this year — {noun} through {month_end}."
            # Multi-year future window — name both ends
            return "LIKELY", f"Likely — {noun} {month_start} through {month_end}."
        # Window already closed (rare but possible if engine surfaced past)
        if next_label:
            return "NOT_THIS_YEAR", f"Not now — next {noun} {next_label}."
        return "NOT_THIS_YEAR", f"Not now — that {noun} has already closed."

    # ── Partial signal — building phase ──────────────────────────────────
    if lock_count == 1:
        if next_label:
            return "NOT_YET", f"Not yet — next {noun} {next_label}."
        return "NOT_YET", f"Not yet — a building phase, no strong {noun}."

    # ── No supportive signal in horizon ──────────────────────────────────
    if next_label:
        return "NO", f"No strong {noun} this cycle — next opening {next_label}."
    return "NO", f"No strong {noun} in the next 24 months."


def _soften_ask_phrase(concern: str, band: str, window_label) -> str:
    """[ask-promise] Rewrite an over-claimed opening: strong timing but a
    weak/absent chart promise. Honest + agency-leaning, keeps the window,
    never says "you don't have this"."""
    noun = _DOMAIN_NOUN.get(concern, "opening")
    wl = window_label or "the months ahead"
    if band == "absent":
        return (f"{noun.capitalize()} isn't a strong natural promise in your "
                f"chart. The supportive window is {wl} — treat it as something to "
                f"work toward with focus and the right practice, not to wait for.")
    return (f"{noun.capitalize()} is a modest promise, not a strong one. The "
            f"window {wl} can still deliver with steady effort and the right support.")


def promise_adjusted_verdict(verdict: str, promise_band) -> str:
    """[slice-3] Reconcile a timing verdict with the chart's promise so the
    client chip never over-claims vs. the softened opening. DOWNGRADE-only,
    existing enums (YES/SUPPORTED/LIKELY/NOT_THIS_YEAR/NOT_YET/NO)."""
    v = (verdict or "").upper()
    b = (promise_band or "").lower()
    if b == "absent" and v in ("YES", "SUPPORTED", "LIKELY"):
        return "NOT_YET"
    if b == "weak" and v in ("YES", "SUPPORTED"):
        return "LIKELY"
    return verdict


def consultation_prompt_block(conv: dict, concern: str, dasha_str: str) -> str:
    """Prompt block pinning the deterministic facts Claude must narrate."""
    if not conv:
        return ""
    locks = conv.get("locks", {})
    lines = [
        "=== CONSULTATION FACTS (deterministic — do NOT alter dates, verdict direction, or the window) ===",
        f"VERDICT (Python-authoritative): {conv.get('verdict', 'NOT_YET')}",
        f"OPENING SENTENCE (Python prepends this verbatim to `read`; do NOT repeat it): {conv.get('verdict_phrase', '')}",
        f"DOMAIN: {concern}",
        f"ACTIVE DASHA: {dasha_str or 'unknown'}",
        "CONVERGENCE CHECK (2-of-3 rule across Vimshottari / Chara dasha / Varshphal):",
    ]
    for name, label in (("vimshottari", "Vimshottari"), ("chara", "Chara dasha"), ("varshphal", "Varshphal")):
        v = locks.get(name, {})
        state = "ACTIVE" if v.get("active") else "inactive"
        lines.append(f"  {label}: {state} — {v.get('why', '')}")
    lines.append(f"RESULT: {conv.get('summary', '')}")
    if conv.get("window_label"):
        lines.append(f"TIMING WINDOW (use this verbatim, plainly worded): {conv['window_label']}")
        if conv.get("window_end"):
            # [narrator-hardbind 2026-06-05c, v2] Relative-duration freelancing
            # ("through the end of the year") slips past the absolute-date
            # scrub — pin the boundary in the prompt. v2: month-level ONLY.
            # Exposing the raw ISO end date made the model narrate day-level
            # urgency ("through June 10th — just five days"); the product
            # speaks in months and never uses scarcity pressure.
            lines.append(
                f"WINDOW DISCIPLINE: the window is {conv['window_label']} — "
                "month-level granularity ONLY. Never stretch it (no 'through "
                "the end of the year', 'in the coming months'), never narrow "
                "it to specific days, never count days remaining, and never "
                "use scarcity pressure ('act immediately', 'won't repeat'). "
                "If the window is open now, advise calm, concrete use of it."
            )
    else:
        lines.append("TIMING WINDOW: none — frame as a building/preparation phase, do NOT invent dates")
    if conv.get("next_window_label"):
        lines.append(f"AFTER THIS WINDOW: next opening {conv['next_window_label']} — {conv.get('next_window_why', '')}")
    _secw = [w.get("label", "") for w in (conv.get("secondary_windows") or []) if w.get("label")]
    if _secw:
        lines.append("ALSO SUPPORTIVE (secondary windows — mention briefly, do not "
                     "over-emphasize): " + "; ".join(_secw))
    # [ask-slice2] agency dial — how hard to lean on when-to-receive vs.
    # what-to-do, from the Stage-1 promise band.
    _band = conv.get("promise_band")
    if _band == "strong":
        lines.append("AGENCY FRAMING: the chart strongly promises this — LEAD with the timing (when to receive it) and how to prepare. Mention any practice lightly, as support, not the headline.")
    elif _band == "moderate":
        lines.append("AGENCY FRAMING: the chart promises this moderately — balance the timing with concrete effort; name the practice or remedy as the way to earn the window.")
    elif _band in ("weak", "absent"):
        lines.append("AGENCY FRAMING: the chart's natural promise here is modest — LEAD with what to DO. The window helps, but effort, the remedy, and the practice are what make it land. Never fatalistic: the user has real agency here.")
    lines.append("=== END CONSULTATION FACTS ===")
    return "\n".join(lines)


def enrich_jaimini_for_locks(jaimini_data, dashas) -> dict:
    """
    Synthesize the keys prashna_engine._check_jaimini_triple_lock expects but
    the stored jaimini_data column lacks (audit 2026-06-03):
      current_mahadasha.lord, current_chara_dasha.sign_index,
      karakas as dict (stored as list), arudha_lagna.sign_index (stored 'sign').
    Without these, all three Jaimini locks silently never fire.
    """
    jd = dict(jaimini_data or {})
    today = date.today()

    if not jd.get("current_mahadasha"):
        for r in _rows(dashas, "vimsottari"):
            if _level(r) in ("mahadasha", "1"):
                s, e = _win(r)
                if s and e and s <= today <= e:
                    jd["current_mahadasha"] = {"lord": _lord(r)}
                    break

    if not jd.get("current_chara_dasha"):
        for r in _rows(dashas, "jaimini"):
            if _level(r) in ("mahadasha", "1"):
                s, e = _win(r)
                sign = _lord(r)
                if s and e and s <= today <= e and sign in SIGNS:
                    jd["current_chara_dasha"] = {"sign_index": SIGNS.index(sign), "sign": sign}
                    break

    k = jd.get("karakas")
    if isinstance(k, list):
        kd = {}
        for item in k:
            if isinstance(item, dict) and item.get("karaka"):
                si = item.get("sign_index", item.get("sign"))
                if isinstance(si, int):
                    kd[item["karaka"]] = {"sign_index": si, "planet": item.get("planet", "")}
        if kd:
            jd["karakas"] = kd

    al = jd.get("arudha_lagna")
    if isinstance(al, dict) and "sign_index" not in al and isinstance(al.get("sign"), int):
        al = dict(al)
        al["sign_index"] = al["sign"]
        jd["arudha_lagna"] = al

    return jd
