"""
antar_engine/ask_consultation.py
=================================
Consultation layer for /api/v1/ask — launch sprint 2026-06-03.

Gives /ask the three-part consultation answer on real, deterministic inputs:
  1. VERDICT + TIMING — from a 2-of-3 convergence across Vimshottari (MD/AD),
     Chara dasha, and Varshphal. Python computes the window; Claude narrates.
  2. ACTIONS — generated by Claude FROM the convergence facts (never invented
     dates — the window is pinned in the prompt).
  3. PRACTICES — markable PracticeCards come from the existing practice
     engine (practice_id linkage to practice_log), assembled in main.py.

Shared primitives with /predict: dasha_periods rows (get_dashas_for_chart
shape), varshaphal_table.get_annual_house, detect_concern domain names.
No LLM calls in this module. No prose duplication of /predict's context.
"""

from __future__ import annotations

from datetime import date, timedelta
from typing import Optional

SIGNS = ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra",
         "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"]

SIGN_LORDS = {
    "Aries": "Mars", "Taurus": "Venus", "Gemini": "Mercury", "Cancer": "Moon",
    "Leo": "Sun", "Virgo": "Mercury", "Libra": "Venus", "Scorpio": "Mars",
    "Sagittarius": "Jupiter", "Capricorn": "Saturn", "Aquarius": "Saturn",
    "Pisces": "Jupiter",
}

# concern (detect_concern names) -> target houses.
# Aligned with /predict's relevant_divisions and prashna DOMAIN_HOUSE_MAP:
# funding/finance = 2nd (cash) + 8th (other people's money) + 11th (gains).
CONCERN_HOUSES = {
    "finance":     [2, 8, 11],
    "funding":     [8, 11, 2],
    "wealth":      [2, 11],
    "loss":        [8, 12, 2],
    "speculation": [5, 2, 11],
    "career":      [10, 6, 11],
    "business":    [7, 10, 11],
    "marriage":    [7],
    "love":        [5, 7],
    "divorce":     [7, 6],
    # [routing-2026-06-07] reconciliation: 7 (partnership), 5 (romance/heart),
    # 4 (emotional foundation / re-building). Distinct from divorce (which
    # looks for separation triggers) — this looks for re-binding signals.
    "reconciliation": [7, 5, 4],
    "health":      [6, 1, 8],
    "foreign":     [12, 9],
    "children":    [5],
    "property":    [4, 2],
    "education":   [5, 9],
    "legal":       [6, 7],
    "spiritual":   [9, 12],
    "general":     [10, 11],
}

# Natural karaka planets per concern — used by the Varshphal lock.
CONCERN_KARAKAS = {
    "finance":     ["Jupiter", "Venus", "Mercury"],
    "funding":     ["Jupiter", "Venus", "Mercury", "Rahu"],
    "wealth":      ["Jupiter", "Venus"],
    "speculation": ["Mercury", "Rahu"],
    "career":      ["Sun", "Saturn", "Mars", "Mercury"],
    "business":    ["Mercury", "Jupiter"],
    "marriage":    ["Venus", "Jupiter"],
    "love":        ["Venus", "Moon"],
    # [routing-2026-06-07] reconciliation karakas — Venus (love/repair),
    # Moon (emotional re-bonding), Jupiter (wisdom/forgiveness).
    "reconciliation": ["Venus", "Moon", "Jupiter"],
    "health":      ["Sun", "Mars"],
    "foreign":     ["Rahu", "Moon"],
    "children":    ["Jupiter"],
    "property":    ["Mars", "Venus"],
    "education":   ["Mercury", "Jupiter"],
    "legal":       ["Jupiter", "Saturn"],
    "spiritual":   ["Ketu", "Jupiter"],
}

# Decision/timing question patterns — EN + ES (live app runs Spanish too).
# Anything in this list routes to build_convergence_timing → real verdict.
# Anything NOT in this list takes the reflective fallback path (no verdict).
# Expanded 2026-06-07 to cover chance/odds/possibility/reunion phrasings the
# audit showed were silently falling through ("is there a chance of reuniting…").
_DECISION_TRIGGERS = [
    # English — direct timing
    "when ", "when?", "by when", "how soon", "how long until",
    "what month", "what year", "which month", "which quarter",
    # English — will/should/can framings
    "will i", "will my", "will we", "will this", "will the", "will it",
    "should i", "should we", "can i ", "could i",
    "do i get", "am i going to",
    # English — good-time framings
    "is it a good time", "right time", "good time to",
    # English — chance / odds / possibility (covers Failure 2)
    "is there a chance", "any chance", "chance of",
    "what are the chances", "what's the chance", "whats the chance",
    "what are my odds", "odds of", "likelihood of", "possibility of",
    "is there hope", "any hope of", "is it possible", "could there be",
    "could we", "could it", "could it be",
    # English — relationship-reunion specific (covers Failure 2 directly)
    "are we getting back", "get back together", "getting back together",
    "back together", "reunite", "reuniting", "reunion",
    "rekindle", "rekindling", "second chance",
    "fix things with", "work things out", "fix it with",
    # English — career / business specific timing intent
    "do i land", "will i land", "what are the chances of landing",
    # Spanish — direct timing
    "cuándo", "cuando ", "conseguiré", "lograré", "obtendré", "recibiré",
    "tendré", "podré",
    "voy a conseguir", "voy a lograr", "voy a recibir",
    "debo ", "debería",
    "es buen momento", "buen momento para",
    "en qué mes", "en que mes", "qué año", "que año",
    # Spanish — chance / odds / possibility
    "hay una posibilidad", "alguna posibilidad", "hay alguna chance",
    "qué probabilidad", "que probabilidad", "qué chance", "que chance",
    "tendré otra oportunidad", "habrá oportunidad",
    "es posible", "es posible que",
    # Spanish — reconciliation
    "volveremos", "reconciliarnos", "reconciliar", "volver con",
    "volver juntos", "rehacer la relación", "una segunda oportunidad",
]


# detect_concern names that the pre-scan's DOMAIN_VOCABULARY / house map
# don't recognize — alias them so no classified question silently falls
# back to DOMAIN: GENERAL (acceptance-test criterion).
PRESCAN_DOMAIN_ALIAS = {
    "love": "relationship", "marriage": "relationship", "divorce": "relationship",
    "reconciliation": "relationship",  # [routing-2026-06-07] reunion questions
    "funding": "finance", "loss": "finance", "speculation": "finance",
    "money": "finance", "billionaire": "wealth", "rich": "wealth",
    "spiritual": "general",
}


def prescan_domain(concern: str) -> str:
    """Map a detect_concern result to a domain the pre-scan understands."""
    return PRESCAN_DOMAIN_ALIAS.get(concern, concern or "general")


def is_decision_question(question: str) -> bool:
    """True if the question wants a verdict and/or a timing window."""
    q = " " + (question or "").lower().strip() + " "
    if q.strip().startswith(("when", "cuándo", "cuando")):
        return True
    return any(t in q for t in _DECISION_TRIGGERS)


# ───────────────────────── row helpers (dasha_periods shape) ─────────────

def _parse_d(s) -> Optional[date]:
    try:
        return date.fromisoformat(str(s)[:10])
    except Exception:
        return None


def _rows(dashas, system):
    return (dashas or {}).get(system, []) or []


def _level(r) -> str:
    return str(r.get("level") or r.get("type", "")).lower()


def _lord(r) -> str:
    return r.get("lord_or_sign") or r.get("planet_or_sign", "")


def _win(r):
    return (_parse_d(r.get("start_date") or r.get("start")),
            _parse_d(r.get("end_date") or r.get("end")))


def _lagna_idx(chart_data) -> int:
    lagna = (chart_data or {}).get("lagna", {})
    if isinstance(lagna, dict):
        si = lagna.get("sign_index")
        if isinstance(si, int) and 0 <= si <= 11:
            return si
        name = lagna.get("sign", "")
    else:
        name = str(lagna)
    return SIGNS.index(name) if name in SIGNS else 0


def _house_lords(lagna_idx) -> dict:
    """Whole-sign house lords computed from the lagna — independent of the
    (string-keyed) chart_data.house_lords column."""
    return {h: SIGN_LORDS[SIGNS[(lagna_idx + h - 1) % 12]] for h in range(1, 13)}


def _fmt_window(s: Optional[date], e: Optional[date]) -> str:
    if not s or not e:
        return ""
    # Same-month window: "Jun 2026 – Jun 2026" reads broken — collapse.
    if (s.year, s.month) == (e.year, e.month):
        return s.strftime("%b %Y")
    return f"{s.strftime('%b %Y')} – {e.strftime('%b %Y')}"


# ───────────────────────── per-system locks ──────────────────────────────

def _vimshottari_lock(dashas, chart_data, houses, lords, today, horizon):
    """Earliest current/upcoming Vimshottari period whose lord rules or
    occupies a target house. AD windows preferred (tighter)."""
    planets = (chart_data or {}).get("planets") or {}

    def qualifies(p):
        if not p:
            return False
        if p in lords:
            return True
        return (planets.get(p) or {}).get("house") in houses

    best = None
    for want_ad in (True, False):
        for r in _rows(dashas, "vimsottari"):
            lv = _level(r)
            is_ad = lv in ("antardasha", "antar", "2")
            is_md = lv in ("mahadasha", "1")
            if want_ad and not is_ad:
                continue
            if not want_ad and not is_md:
                continue
            s, e = _win(r)
            if not s or not e or e < today or s > horizon:
                continue
            p = _lord(r)
            if qualifies(p):
                cs, ce = max(s, today), min(e, horizon)
                if best is None or cs < best[1]:
                    kind = "sub-chapter" if is_ad else "chapter"
                    role = "rules" if p in lords else "occupies"
                    best = (p, cs, ce, f"{p} {kind} {role} a target area, {_fmt_window(cs, ce)}")
        if best:
            break
    if best:
        return {"active": True, "start": best[1], "end": best[2], "why": best[3], "planet": best[0]}
    return {"active": False, "start": None, "end": None, "why": "no period lord touches the target areas in the horizon", "planet": ""}


def _next_vim_window(dashas, chart_data, houses, lords, after, horizon):
    """Earliest qualifying Vimshottari window STARTING after `after` —
    surfaces the next opening when the current window is the tail of an
    ending chapter (e.g. funding: Mars MD ends Aug 2026, Rahu in the gains
    area takes over)."""
    planets = (chart_data or {}).get("planets") or {}

    def qualifies(p):
        if not p:
            return False
        if p in lords:
            return True
        return (planets.get(p) or {}).get("house") in houses

    best = None
    for r in _rows(dashas, "vimsottari"):
        lv = _level(r)
        if lv not in ("antardasha", "antar", "2", "mahadasha", "1"):
            continue
        s, e = _win(r)
        # s >= after keeps same-day chapter handoffs (e.g. Mars ends Aug 13,
        # Rahu starts Aug 13) — but skip rows already underway before `after`
        if not s or not e or s < after or s > horizon:
            continue
        p = _lord(r)
        if qualifies(p) and (best is None or s < best[1]):
            kind = "sub-chapter" if lv in ("antardasha", "antar", "2") else "chapter"
            role = "rules" if p in lords else "occupies"
            best = (p, s, min(e, horizon), f"{p} {kind} ({role} a target area) opens {s.strftime('%b %Y')}")
    if best:
        return {"planet": best[0], "start": best[1], "end": best[2],
                "label": _fmt_window(best[1], best[2]), "why": best[3]}
    return None


def _chara_lock(dashas, lagna_idx, houses, lords, today, horizon):
    """Earliest current/upcoming Chara sign period that activates a target
    house (sign sits in a target house from lagna, or sign's lord is a
    target-house lord). AD sign periods preferred."""
    best = None
    for want_ad in (True, False):
        for r in _rows(dashas, "jaimini"):
            lv = _level(r)
            is_ad = lv in ("antardasha", "antar", "2")
            is_md = lv in ("mahadasha", "1")
            if want_ad and not is_ad:
                continue
            if not want_ad and not is_md:
                continue
            sign = _lord(r)
            if sign not in SIGNS:
                continue
            s, e = _win(r)
            if not s or not e or e < today or s > horizon:
                continue
            sign_house = (SIGNS.index(sign) - lagna_idx) % 12 + 1
            _by_house = sign_house in houses
            _by_lord = SIGN_LORDS[sign] in lords
            if _by_house or _by_lord:
                cs, ce = max(s, today), min(e, horizon)
                if best is None or cs < best[1]:
                    kind = "sub-period" if is_ad else "period"
                    if _by_house:
                        reason = f"sits in target house {sign_house}"
                    else:
                        reason = f"its lord {SIGN_LORDS[sign]} rules a target area"
                    best = (sign, cs, ce,
                            f"{sign} {kind} {reason}, {_fmt_window(cs, ce)}")
        if best:
            break
    if best:
        return {"active": True, "start": best[1], "end": best[2], "why": best[3],
                "planet": SIGN_LORDS.get(best[0], "")}
    return {"active": False, "start": None, "end": None, "why": "no sign period activates the target areas in the horizon", "planet": ""}


def _varshphal_lock(chart_data, birth_date, houses, lords, karakas, today):
    """Does this Varshphal year send a domain-relevant planet (target-house
    lord or natural karaka) into a target annual house? Window = the annual
    chart's validity (birthday to birthday). Same get_annual_house as /predict."""
    born = _parse_d(birth_date)
    if not born:
        return {"active": False, "start": None, "end": None, "why": "birth date unavailable"}
    try:
        from antar_engine.varshaphal_table import get_annual_house
    except Exception:
        return {"active": False, "start": None, "end": None, "why": "varshphal table unavailable"}

    age = (today - born).days // 365
    try:
        last_bday = born.replace(year=today.year)
    except ValueError:  # Feb 29
        last_bday = born.replace(year=today.year, day=28)
    if last_bday > today:
        last_bday = last_bday.replace(year=last_bday.year - 1)
    next_bday = last_bday.replace(year=last_bday.year + 1)

    relevant = set(lords) | set(karakas)
    hits, hit_planets = [], []
    for p, d in ((chart_data or {}).get("planets") or {}).items():
        nh = d.get("house") if isinstance(d, dict) else None
        if nh and 1 <= nh <= 12 and p in relevant:
            ah = get_annual_house(nh, age)
            if ah in houses:
                hits.append(f"{p} lands in annual house {ah}")
                hit_planets.append(p)
    if hits:
        return {"active": True, "start": last_bday, "end": next_bday,
                "why": "; ".join(hits[:3]) + f", valid {_fmt_window(last_bday, next_bday)}",
                "planet": hit_planets[0]}
    return {"active": False, "start": last_bday, "end": next_bday,
            "why": "this year's chart does not move relevant planets into the target areas",
            "planet": ""}


# ───────────────────────── convergence (2-of-3) ──────────────────────────

def build_convergence_timing(concern, chart_data, dashas, birth_date,
                             horizon_months: int = 24) -> dict:
    """
    Deterministic 2-of-3 convergence across Vimshottari + Chara + Varshphal.
    Returns lock states, lock_count, convergence_met, and a timing window
    (overlap of the agreeing systems' windows, clipped to the horizon).
    """
    today = date.today()
    horizon = today + timedelta(days=horizon_months * 30)
    houses = CONCERN_HOUSES.get(concern, CONCERN_HOUSES["general"])
    karakas = CONCERN_KARAKAS.get(concern, ["Jupiter", "Sun"])
    lagna_idx = _lagna_idx(chart_data)
    lords = {_house_lords(lagna_idx)[h] for h in houses}

    locks = {
        "vimshottari": _vimshottari_lock(dashas, chart_data, houses, lords, today, horizon),
        "chara":       _chara_lock(dashas, lagna_idx, houses, lords, today, horizon),
        "varshphal":   _varshphal_lock(chart_data, birth_date, houses, lords, karakas, today),
    }
    lock_count = sum(1 for v in locks.values() if v["active"])
    convergence_met = lock_count >= 2

    # Domain-relevant planets — active lock planets first, then target-house
    # lords, then natural karakas. Used to pick domain-matched practices.
    relevant_planets = []
    for v in locks.values():
        p = v.get("planet")
        if p and p not in relevant_planets:
            relevant_planets.append(p)
    for p in list(lords) + list(karakas):
        if p and p not in relevant_planets:
            relevant_planets.append(p)

    window_start = window_end = None
    if convergence_met:
        active = [(v["start"], v["end"]) for v in locks.values()
                  if v["active"] and v["start"] and v["end"]]
        # best pairwise overlap, earliest start wins
        best = None
        for i in range(len(active)):
            for j in range(i + 1, len(active)):
                s = max(active[i][0], active[j][0])
                e = min(active[i][1], active[j][1])
                if s <= e and (best is None or s < best[0]):
                    best = (s, e)
        if best:
            window_start, window_end = best
        else:
            # systems agree the theme is active but in staggered windows —
            # surface the earliest one honestly
            active.sort(key=lambda w: w[0])
            window_start, window_end = active[0]

    # Next opening after the current window (or after today if none) — e.g.
    # funding: Mars chapter tail ends Aug 2026, Rahu opens the gains area next.
    next_win = _next_vim_window(dashas, chart_data, houses, lords,
                                window_end or today, horizon)

    window_label = _fmt_window(window_start, window_end)
    if convergence_met and window_label:
        summary = f"{lock_count} of 3 timing systems converge: window {window_label}"
        public_summary = f"{lock_count} of 3 timing systems point to {window_label}"
    elif lock_count == 1:
        only = next(k for k, v in locks.items() if v["active"])
        summary = f"1 of 3 systems active ({only}) — no convergence; treat as a building phase"
        public_summary = "1 of 3 timing systems active — building phase, no strong window yet"
    else:
        summary = "0 of 3 systems active — no supportive window inside the horizon"
        public_summary = "No strong timing window in the next 24 months — building phase"

    _conv_for_verdict = {
        "lock_count": lock_count,
        "convergence_met": convergence_met,
        "window_start": window_start.isoformat() if window_start else None,
        "window_end": window_end.isoformat() if window_end else None,
        "next_window_label": (next_win or {}).get("label"),
    }
    _verdict, _verdict_phrase = _derive_verdict_phrase(
        _conv_for_verdict, concern, date.today())
    return {
        "concern": concern,
        "houses": houses,
        "locks": {k: {"active": v["active"], "why": v["why"],
                      "window": _fmt_window(v["start"], v["end"])}
                  for k, v in locks.items()},
        "lock_count": lock_count,
        "convergence_met": convergence_met,
        "window_start": window_start.isoformat() if window_start else None,
        "window_end": window_end.isoformat() if window_end else None,
        "window_label": window_label or None,
        "next_window_label": (next_win or {}).get("label"),
        "next_window_why": (next_win or {}).get("why"),
        "relevant_planets": relevant_planets,
        "summary": summary,
        "public_summary": public_summary,
        "verdict":        _verdict,         # [lead-verdict]
        "verdict_phrase": _verdict_phrase,  # [lead-verdict]
    }


# Domain-specific noun for the deterministic opening sentence ("funding window",
# "partnership window", "career opening"). Keep nouns SHORT and concrete — the
# whole point is to drop vague energy-talk and lead with a real-noun + date.
_DOMAIN_NOUN = {
    "finance":     "funding window",
    "funding":     "funding window",
    "wealth":      "money window",
    "loss":        "financial window",
    "speculation": "speculative window",
    "career":      "career window",
    "business":    "business window",
    "marriage":    "partnership window",
    "love":        "partnership window",
    "divorce":     "partnership transition",
    "reconciliation": "reconnection window",
    "health":      "health window",
    "foreign":     "relocation window",
    "children":    "family window",
    "property":    "property window",
    "education":   "education window",
    "legal":       "legal window",
    "spiritual":   "spiritual window",
    "general":     "opening",
}


def _derive_verdict_phrase(conv: dict, concern: str, today: date) -> tuple:
    """
    Python-authoritative opening sentence for /ask. Returns (verdict_enum,
    verdict_phrase) where:
      verdict_enum   ∈ {SUPPORTED, LIKELY, NOT_THIS_YEAR, NOT_YET, NO}
      verdict_phrase = exact sentence the narrator's `read` must open with.

    The phrase is deterministic — built from the engine's lock_count, window
    bounds, and the domain noun. Never invents dates; only restates what the
    convergence engine produced.
    """
    noun = _DOMAIN_NOUN.get(concern, "opening")
    lock_count      = int(conv.get("lock_count") or 0)
    convergence_met = bool(conv.get("convergence_met"))
    ws_str          = conv.get("window_start")
    we_str          = conv.get("window_end")
    next_label      = conv.get("next_window_label") or ""

    try:
        ws = date.fromisoformat(ws_str) if ws_str else None
    except Exception:
        ws = None
    try:
        we = date.fromisoformat(we_str) if we_str else None
    except Exception:
        we = None

    # ── Convergence + window — the strong answers ────────────────────────
    if convergence_met and ws and we:
        if ws <= today <= we:
            month_end = we.strftime("%B %Y")
            return "SUPPORTED", f"Yes — {noun} is open now, through {month_end}."
        if ws > today:
            month_start = ws.strftime("%B %Y")
            month_end   = we.strftime("%B %Y")
            # Same calendar year as today → "this year, through {month_end}"
            if ws.year == today.year and we.year == today.year:
                return "LIKELY", f"Likely, this year — {noun} through {month_end}."
            # Multi-year future window — name both ends
            return "LIKELY", f"Likely — {noun} {month_start} through {month_end}."
        # Window already closed (rare but possible if engine surfaced past)
        if next_label:
            return "NOT_THIS_YEAR", f"Not now — next {noun} {next_label}."
        return "NOT_THIS_YEAR", f"Not now — that {noun} has already closed."

    # ── Partial signal — building phase ──────────────────────────────────
    if lock_count == 1:
        if next_label:
            return "NOT_YET", f"Not yet — next {noun} {next_label}."
        return "NOT_YET", f"Not yet — a building phase, no strong {noun}."

    # ── No supportive signal in horizon ──────────────────────────────────
    if next_label:
        return "NO", f"No strong {noun} this cycle — next opening {next_label}."
    return "NO", f"No strong {noun} in the next 24 months."


def consultation_prompt_block(conv: dict, concern: str, dasha_str: str) -> str:
    """Prompt block pinning the deterministic facts Claude must narrate."""
    if not conv:
        return ""
    locks = conv.get("locks", {})
    lines = [
        "=== CONSULTATION FACTS (deterministic — do NOT alter dates, verdict direction, or the window) ===",
        f"VERDICT (Python-authoritative): {conv.get('verdict', 'NOT_YET')}",
        f"OPENING SENTENCE (Python prepends this verbatim to `read`; do NOT repeat it): {conv.get('verdict_phrase', '')}",
        f"DOMAIN: {concern}",
        f"ACTIVE DASHA: {dasha_str or 'unknown'}",
        "CONVERGENCE CHECK (2-of-3 rule across Vimshottari / Chara dasha / Varshphal):",
    ]
    for name, label in (("vimshottari", "Vimshottari"), ("chara", "Chara dasha"), ("varshphal", "Varshphal")):
        v = locks.get(name, {})
        state = "ACTIVE" if v.get("active") else "inactive"
        lines.append(f"  {label}: {state} — {v.get('why', '')}")
    lines.append(f"RESULT: {conv.get('summary', '')}")
    if conv.get("window_label"):
        lines.append(f"TIMING WINDOW (use this verbatim, plainly worded): {conv['window_label']}")
        if conv.get("window_end"):
            # [narrator-hardbind 2026-06-05c, v2] Relative-duration freelancing
            # ("through the end of the year") slips past the absolute-date
            # scrub — pin the boundary in the prompt. v2: month-level ONLY.
            # Exposing the raw ISO end date made the model narrate day-level
            # urgency ("through June 10th — just five days"); the product
            # speaks in months and never uses scarcity pressure.
            lines.append(
                f"WINDOW DISCIPLINE: the window is {conv['window_label']} — "
                "month-level granularity ONLY. Never stretch it (no 'through "
                "the end of the year', 'in the coming months'), never narrow "
                "it to specific days, never count days remaining, and never "
                "use scarcity pressure ('act immediately', 'won't repeat'). "
                "If the window is open now, advise calm, concrete use of it."
            )
    else:
        lines.append("TIMING WINDOW: none — frame as a building/preparation phase, do NOT invent dates")
    if conv.get("next_window_label"):
        lines.append(f"AFTER THIS WINDOW: next opening {conv['next_window_label']} — {conv.get('next_window_why', '')}")
    lines.append("=== END CONSULTATION FACTS ===")
    return "\n".join(lines)


def enrich_jaimini_for_locks(jaimini_data, dashas) -> dict:
    """
    Synthesize the keys prashna_engine._check_jaimini_triple_lock expects but
    the stored jaimini_data column lacks (audit 2026-06-03):
      current_mahadasha.lord, current_chara_dasha.sign_index,
      karakas as dict (stored as list), arudha_lagna.sign_index (stored 'sign').
    Without these, all three Jaimini locks silently never fire.
    """
    jd = dict(jaimini_data or {})
    today = date.today()

    if not jd.get("current_mahadasha"):
        for r in _rows(dashas, "vimsottari"):
            if _level(r) in ("mahadasha", "1"):
                s, e = _win(r)
                if s and e and s <= today <= e:
                    jd["current_mahadasha"] = {"lord": _lord(r)}
                    break

    if not jd.get("current_chara_dasha"):
        for r in _rows(dashas, "jaimini"):
            if _level(r) in ("mahadasha", "1"):
                s, e = _win(r)
                sign = _lord(r)
                if s and e and s <= today <= e and sign in SIGNS:
                    jd["current_chara_dasha"] = {"sign_index": SIGNS.index(sign), "sign": sign}
                    break

    k = jd.get("karakas")
    if isinstance(k, list):
        kd = {}
        for item in k:
            if isinstance(item, dict) and item.get("karaka"):
                si = item.get("sign_index", item.get("sign"))
                if isinstance(si, int):
                    kd[item["karaka"]] = {"sign_index": si, "planet": item.get("planet", "")}
        if kd:
            jd["karakas"] = kd

    al = jd.get("arudha_lagna")
    if isinstance(al, dict) and "sign_index" not in al and isinstance(al.get("sign"), int):
        al = dict(al)
        al["sign_index"] = al["sign"]
        jd["arudha_lagna"] = al

    return jd
