"""
antar_engine/practice_library.py
─────────────────────────────────────────────────────────────────────────────
Practice content — ONE source of truth per planet.  Phase 1 (redesign).

Hard rule enforced by construction: a planet's remediation only ever draws
content from that planet's entry.  A Saturn remediation can never surface
Mercury content.

Prose fields that reach the user (governs / symptoms / affirmation /
why_this_works / daily_action.detail) carry {en, es}.  Mantra Sanskrit /
transliteration are language-neutral.  Body cue and breath pattern are kept
technical (English); they are short and instruction-like.
"""

from __future__ import annotations


def _loc(field, lang: str):
    """Pick en/es from a bilingual field; pass through plain values."""
    if isinstance(field, dict) and ("en" in field or "es" in field):
        l = "es" if str(lang).lower().startswith("es") else "en"
        return field.get(l) or field.get("en")
    return field


PRACTICE_LIBRARY = {
    "Sun": {
        "what_it_governs": {"en": "Authority, vitality, confidence, recognition, the father, the self at its center.",
                            "es": "Autoridad, vitalidad, confianza, reconocimiento, el padre, el yo en su centro."},
        "when_weak_symptoms": {"en": "Confidence flickers, recognition slips away, authority figures feel like obstacles, low vitality.",
                              "es": "La confianza vacila, el reconocimiento se escapa, las figuras de autoridad se sienten como obstáculos, baja vitalidad."},
        "mantra": {"primary": "Om Hraam Hreem Hraum Sah Suryaya Namaha", "sanskrit": "ॐ ह्रां ह्रीं ह्रौं सः सूर्याय नमः",
                   "translit": "OM HRAAM HREEM HRAUM SAH SURYAYA NAMAHA", "count": 108, "duration_minutes": 15,
                   "when": "At sunrise, facing east"},
        "body": {"name": "Sun Salutation (Surya Namaskar)", "minutes": 5,
                 "cue": "Move with the breath. Reach tall on the inhale, fold with the exhale. Let the spine wake from the base up."},
        "breath": {"name": "Bright Breath (Kapalabhati, gentle)", "pattern": "Short active exhales, passive inhales", "rounds": 3},
        "daily_action": {"title": "Offer water to the rising Sun",
                         "detail": {"en": "At sunrise, offer water from a copper vessel toward the Sun. Donate wheat or jaggery on Sundays. Respect your father and elders.",
                                    "es": "Al amanecer, ofrece agua desde un recipiente de cobre hacia el Sol. Dona trigo o panela los domingos. Honra a tu padre y a los mayores."},
                         "frequency": "Every Sunday for 9 weeks"},
        "affirmation": {"en": "I take up my space. My worth does not need permission. I shine without apology.",
                        "es": "Ocupo mi espacio. Mi valor no necesita permiso. Brillo sin disculparme."},
        "chakras_balanced": ["heart", "solar_plexus"],
        "why_this_works": {"en": "The Sun rules the steady core of confidence and vitality. When weak, the self dims and recognition won't land. The seed mantra rekindles that central fire, the morning movement floods the body with light, and the Lal Kitab offering discharges the debt that keeps the Sun shadowed.",
                          "es": "El Sol rige el núcleo estable de la confianza y la vitalidad. Cuando está débil, el yo se atenúa y el reconocimiento no llega. El mantra semilla reaviva ese fuego central, el movimiento matinal inunda el cuerpo de luz, y la ofrenda de Lal Kitab descarga la deuda que mantiene al Sol en sombra."},
        "frequency_hz": 126,
    },
    "Moon": {
        "what_it_governs": {"en": "Emotion, mind, comfort, the mother, memory, how you are received by others.",
                            "es": "Emoción, mente, comodidad, la madre, la memoria, cómo te reciben los demás."},
        "when_weak_symptoms": {"en": "Mood swings, restlessness, feeling unsupported, poor sleep, emotional reactivity.",
                              "es": "Cambios de humor, inquietud, sentirte sin apoyo, mal sueño, reactividad emocional."},
        "mantra": {"primary": "Om Shraam Shreem Shraum Sah Chandraya Namaha", "sanskrit": "ॐ श्रां श्रीं श्रौं सः चन्द्राय नमः",
                   "translit": "OM SHRAAM SHREEM SHRAUM SAH CHANDRAYA NAMAHA", "count": 108, "duration_minutes": 15,
                   "when": "Monday evening, near water or moonlight"},
        "body": {"name": "Reclined Bound Angle (Supta Baddha Konasana)", "minutes": 5,
                 "cue": "Lie back, soles together, knees wide. Let gravity open the chest. Soften the belly with every exhale."},
        "breath": {"name": "Ocean Breath (Ujjayi)", "pattern": "Slow inhale and exhale with a soft throat hush", "rounds": 12},
        "daily_action": {"title": "Offer milk / keep silver",
                         "detail": {"en": "On Mondays, offer milk to flowing water or at a Shiva temple. Keep a small silver article with you. Care for your mother.",
                                    "es": "Los lunes, ofrece leche a agua corriente o en un templo de Shiva. Lleva contigo un pequeño objeto de plata. Cuida de tu madre."},
                         "frequency": "Every Monday for 9 weeks"},
        "affirmation": {"en": "I am safe to feel. My emotions are weather, not walls. I let comfort in.",
                        "es": "Es seguro sentir. Mis emociones son clima, no muros. Dejo entrar la calma."},
        "chakras_balanced": ["sacral", "third_eye"],
        "why_this_works": {"en": "The Moon rules the emotional baseline and the felt sense of safety. When weak, the mind churns and rest won't come. The mantra steadies the inner tide, the restorative posture signals safety to the nervous system, and the silver and milk are the Lal Kitab way of feeding the Moon.",
                          "es": "La Luna rige la base emocional y la sensación de seguridad. Cuando está débil, la mente se agita y el descanso no llega. El mantra calma la marea interior, la postura restaurativa le indica seguridad al sistema nervioso, y la plata y la leche son la forma de Lal Kitab de alimentar a la Luna."},
        "frequency_hz": 210,
    },
    "Mars": {
        "what_it_governs": {"en": "Drive, courage, energy, action, boundaries, siblings, the will to push.",
                            "es": "Impulso, coraje, energía, acción, límites, hermanos, la voluntad de empujar."},
        "when_weak_symptoms": {"en": "Energy runs out fast, anger leaks sideways, plans stall, boundaries collapse, accidents and friction.",
                              "es": "La energía se agota rápido, la ira se filtra de lado, los planes se estancan, los límites colapsan, fricción y accidentes."},
        "mantra": {"primary": "Om Kram Kreem Kraum Sah Bhaumaya Namaha", "sanskrit": "ॐ क्रां क्रीं क्रौं सः भौमाय नमः",
                   "translit": "OM KRAM KREEM KRAUM SAH BHAUMAYA NAMAHA", "count": 108, "duration_minutes": 15,
                   "when": "Tuesday morning, facing south"},
        "body": {"name": "Warrior II (Virabhadrasana II)", "minutes": 4,
                 "cue": "Front knee bent, arms wide and steady. Gaze past the front hand. Feel power without strain."},
        "breath": {"name": "Bellows Breath (Bhastrika, moderate)", "pattern": "Equal forceful inhale and exhale", "rounds": 6},
        "daily_action": {"title": "Give sweets at a Hanuman temple / donate red lentils",
                         "detail": {"en": "On Tuesdays, offer sweets at a Hanuman temple or donate red masoor lentils. Channel anger into physical work, not people.",
                                    "es": "Los martes, ofrece dulces en un templo de Hanuman o dona lentejas rojas (masoor). Canaliza la ira en trabajo físico, no en las personas."},
                         "frequency": "Every Tuesday for 9 weeks"},
        "affirmation": {"en": "My energy is mine to direct. I act with aim, not heat. I hold my ground cleanly.",
                        "es": "Mi energía es mía para dirigir. Actúo con dirección, no con calor. Sostengo mi lugar con limpieza."},
        "chakras_balanced": ["root", "solar_plexus"],
        "why_this_works": {"en": "Mars rules drive and clean boundaries. When weak, energy leaks and force turns to friction. The mantra tempers the fire, the strong stance retrains controlled power, and the Tuesday offering settles Mars's karmic charge the Lal Kitab way.",
                          "es": "Marte rige el impulso y los límites limpios. Cuando está débil, la energía se filtra y la fuerza se vuelve fricción. El mantra templa el fuego, la postura firme reentrena el poder controlado, y la ofrenda del martes asienta la carga kármica de Marte al modo de Lal Kitab."},
        "frequency_hz": 144,
    },
    "Mercury": {
        "what_it_governs": {"en": "Communication, analysis, learning, words, transactions, networks.",
                            "es": "Comunicación, análisis, aprendizaje, palabras, transacciones, redes."},
        "when_weak_symptoms": {"en": "Words don't land, deals stall, ideas feel stuck, brain fog, miscommunication compounds.",
                              "es": "Las palabras no aterrizan, los tratos se estancan, las ideas se atascan, niebla mental, la mala comunicación se acumula."},
        "mantra": {"primary": "Om Bum Budhaye Namaha", "sanskrit": "ॐ बुं बुधाय नमः",
                   "translit": "OM BUM BUDHAYE NAMAHA", "count": 108, "duration_minutes": 15,
                   "when": "Wednesday morning, or any morning before important conversations"},
        "body": {"name": "Seated Spinal Twist (Ardha Matsyendrasana)", "minutes": 3,
                 "cue": "Spine long. Twist from the navel, not the shoulders. Breathe into the kidneys."},
        "breath": {"name": "Alternate Nostril Breathing (Nadi Shodhana)", "pattern": "Inhale left, exhale right, inhale right, exhale left", "rounds": 9},
        "daily_action": {"title": "Donate green moong dal, feed a cow",
                         "detail": {"en": "On Wednesday, give green moong dal to someone who needs it, or feed fresh green grass to a cow. If no cow, scatter green vegetables for birds.",
                                    "es": "El miércoles, da moong dal verde a quien lo necesite, o alimenta con pasto verde fresco a una vaca. Si no hay vaca, esparce verduras verdes para las aves."},
                         "frequency": "Every Wednesday for 9 weeks"},
        "affirmation": {"en": "My words land. My thinking is clear. I speak only what is true and useful.",
                        "es": "Mis palabras aterrizan. Mi pensamiento es claro. Solo digo lo que es verdadero y útil."},
        "chakras_balanced": ["throat", "third_eye"],
        "why_this_works": {"en": "Mercury rules the channels through which thought becomes word and word becomes action. When weak, those channels jam. The mantra clears the seed-vibration, the breath rebalances the hemispheres, and the daily action discharges Mercury's karmic debts in Lal Kitab form.",
                          "es": "Mercurio rige los canales por los que el pensamiento se vuelve palabra y la palabra se vuelve acción. Cuando está débil, esos canales se atascan. El mantra limpia la vibración semilla, la respiración reequilibra los hemisferios, y la acción diaria descarga las deudas kármicas de Mercurio al modo de Lal Kitab."},
        "frequency_hz": 282,
    },
    "Jupiter": {
        "what_it_governs": {"en": "Wisdom, growth, fortune, teachers, faith, expansion, generosity.",
                            "es": "Sabiduría, crecimiento, fortuna, maestros, fe, expansión, generosidad."},
        "when_weak_symptoms": {"en": "Growth stalls, opportunities dry up, faith wavers, advisors mislead, a sense of contraction.",
                              "es": "El crecimiento se estanca, las oportunidades se secan, la fe flaquea, los consejeros confunden, una sensación de contracción."},
        "mantra": {"primary": "Om Graam Greem Graum Sah Gurave Namaha", "sanskrit": "ॐ ग्रां ग्रीं ग्रौं सः गुरवे नमः",
                   "translit": "OM GRAAM GREEM GRAUM SAH GURAVE NAMAHA", "count": 108, "duration_minutes": 15,
                   "when": "Thursday morning, facing northeast"},
        "body": {"name": "Tree Pose (Vrksasana)", "minutes": 4,
                 "cue": "Root one foot down, lift the other to the inner leg. Grow tall through the crown. Steady, not rigid."},
        "breath": {"name": "Three-Part Breath (Dirga)", "pattern": "Fill belly, ribs, chest; empty in reverse", "rounds": 9},
        "daily_action": {"title": "Donate yellow / respect teachers",
                         "detail": {"en": "On Thursdays, donate yellow items — turmeric, chana dal, yellow sweets — and offer respect to a teacher or mentor.",
                                    "es": "Los jueves, dona objetos amarillos — cúrcuma, chana dal, dulces amarillos — y muestra respeto a un maestro o mentor."},
                         "frequency": "Every Thursday for 9 weeks"},
        "affirmation": {"en": "I make room to grow. I trust that good arrives. I give, and the channel opens.",
                        "es": "Hago espacio para crecer. Confío en que el bien llega. Doy, y el canal se abre."},
        "chakras_balanced": ["crown", "sacral"],
        "why_this_works": {"en": "Jupiter rules expansion and grace. When weak, the world feels stingy and growth dries up. The mantra reopens the channel of fortune, the balancing posture trains steady uprightness, and the Thursday giving discharges Jupiter's debt the Lal Kitab way — generosity restores the flow.",
                          "es": "Júpiter rige la expansión y la gracia. Cuando está débil, el mundo se siente tacaño y el crecimiento se seca. El mantra reabre el canal de la fortuna, la postura de equilibrio entrena una verticalidad estable, y la entrega del jueves descarga la deuda de Júpiter al modo de Lal Kitab — la generosidad restaura el flujo."},
        "frequency_hz": 183,
    },
    "Venus": {
        "what_it_governs": {"en": "Love, beauty, pleasure, relationships, art, value, harmony.",
                            "es": "Amor, belleza, placer, relaciones, arte, valor, armonía."},
        "when_weak_symptoms": {"en": "Relationships feel dry, pleasure goes flat, money won't flow, a loss of taste and ease.",
                              "es": "Las relaciones se sienten secas, el placer se apaga, el dinero no fluye, pérdida del gusto y la soltura."},
        "mantra": {"primary": "Om Draam Dreem Draum Sah Shukraya Namaha", "sanskrit": "ॐ द्रां द्रीं द्रौं सः शुक्राय नमः",
                   "translit": "OM DRAAM DREEM DRAUM SAH SHUKRAYA NAMAHA", "count": 108, "duration_minutes": 15,
                   "when": "Friday morning, facing southeast"},
        "body": {"name": "Camel Pose (Ustrasana, gentle)", "minutes": 3,
                 "cue": "Open the front of the heart. Hands to the lower back or heels. Lead with the chest, not the chin."},
        "breath": {"name": "Heart-Smiling Breath", "pattern": "Inhale 5 · soft hold 2 · exhale 6", "rounds": 9},
        "daily_action": {"title": "Donate white / care for women in the family",
                         "detail": {"en": "On Fridays, donate white items — sugar, rice, white cloth — and offer kindness or a gift to the women in your family.",
                                    "es": "Los viernes, dona objetos blancos — azúcar, arroz, tela blanca — y ofrece amabilidad o un regalo a las mujeres de tu familia."},
                         "frequency": "Every Friday for 9 weeks"},
        "affirmation": {"en": "I am worthy of sweetness. I let love and beauty in. Value flows to me with ease.",
                        "es": "Merezco la dulzura. Dejo entrar el amor y la belleza. El valor fluye hacia mí con soltura."},
        "chakras_balanced": ["heart", "sacral"],
        "why_this_works": {"en": "Venus rules sweetness, relating, and the flow of value. When weak, connection and pleasure go flat. The mantra restores the seed-tone of harmony, the heart-opening posture softens defended places, and the Friday giving settles Venus's debt the Lal Kitab way.",
                          "es": "Venus rige la dulzura, el vínculo y el flujo del valor. Cuando está débil, la conexión y el placer se apagan. El mantra restaura el tono semilla de la armonía, la postura que abre el pecho ablanda lo defendido, y la entrega del viernes asienta la deuda de Venus al modo de Lal Kitab."},
        "frequency_hz": 221,
    },
    "Saturn": {
        "what_it_governs": {"en": "Structure, discipline, time, slow build, responsibility, fathers, elders, work that compounds.",
                            "es": "Estructura, disciplina, tiempo, construcción lenta, responsabilidad, mayores, el trabajo que se capitaliza."},
        "when_weak_symptoms": {"en": "Work that won't compound, plans that stall, conflict around responsibility, fear of authority, chronic procrastination.",
                              "es": "Trabajo que no cuaja, planes que se estancan, conflicto en torno a la responsabilidad, miedo a la autoridad, procrastinación crónica."},
        "mantra": {"primary": "Om Sham Shanaye Namaha", "sanskrit": "ॐ शं शनैश्चराय नमः",
                   "translit": "OM SHAM SHANAISHCHARAYA NAMAHA", "count": 108, "duration_minutes": 15,
                   "when": "Before sunset, facing west"},
        "body": {"name": "Mountain Pose (Tadasana)", "minutes": 3,
                 "cue": "Feet planted. Spine long. Crown lifting. Shoulders softening. Feel the weight evenly through both feet."},
        "breath": {"name": "Extended Exhale", "pattern": "Inhale 4 · Exhale 8", "rounds": 9},
        "daily_action": {"title": "Feed black dogs / give black sesame to crows",
                         "detail": {"en": "On a Saturday, give roti mixed with black sesame oil to a black dog, or scatter black sesame seeds where crows gather. Don't tell anyone you did this.",
                                    "es": "Un sábado, da roti con aceite de sésamo negro a un perro negro, o esparce semillas de sésamo negro donde se reúnen los cuervos. No le cuentes a nadie que lo hiciste."},
                         "frequency": "Every Saturday for 9 weeks"},
        "affirmation": {"en": "I move at the pace of building. I let what's slow be slow. I trust the long arc.",
                        "es": "Avanzo al ritmo de la construcción. Dejo que lo lento sea lento. Confío en el arco largo."},
        "chakras_balanced": ["root", "throat"],
        "why_this_works": {"en": "Saturn rules slow-build, structure, and patience. When weak, time itself feels antagonistic — deadlines slip, momentum dies. The mantra is the seed sound of Saturn's energy; the daily action discharges karmic debt the way Lal Kitab prescribes; the body practice trains the nervous system to settle into Saturn's rhythm. None of this is fast. That's the point.",
                          "es": "Saturno rige la construcción lenta, la estructura y la paciencia. Cuando está débil, el tiempo mismo se siente antagonista — los plazos resbalan, el impulso muere. El mantra es el sonido semilla de la energía de Saturno; la acción diaria descarga la deuda kármica como prescribe Lal Kitab; la práctica corporal entrena al sistema nervioso a asentarse en el ritmo de Saturno. Nada de esto es rápido. Ese es el punto."},
        "frequency_hz": 295,
    },
    "Rahu": {
        "what_it_governs": {"en": "Ambition, the foreign and unconventional, obsession, sudden change, hunger for more.",
                            "es": "Ambición, lo extranjero y no convencional, obsesión, cambio súbito, hambre de más."},
        "when_weak_symptoms": {"en": "Anxiety, scattered obsession, confusion, sudden disruptions, chasing things that don't satisfy.",
                              "es": "Ansiedad, obsesión dispersa, confusión, disrupciones súbitas, perseguir cosas que no satisfacen."},
        "mantra": {"primary": "Om Bhraam Bhreem Bhraum Sah Rahave Namaha", "sanskrit": "ॐ भ्रां भ्रीं भ्रौं सः राहवे नमः",
                   "translit": "OM BHRAAM BHREEM BHRAUM SAH RAHAVE NAMAHA", "count": 108, "duration_minutes": 15,
                   "when": "Saturday at dusk, facing southwest"},
        "body": {"name": "Legs-Up-the-Wall (Viparita Karani)", "minutes": 6,
                 "cue": "Legs resting up the wall, arms wide. Let the racing mind drain downward. Nothing to chase here."},
        "breath": {"name": "Long Exhale with Pause", "pattern": "Inhale 4 · Exhale 6 · Pause 4", "rounds": 9},
        "daily_action": {"title": "Feed crows / donate to the marginalized",
                         "detail": {"en": "Feed crows regularly. On Saturdays, donate to people on the margins — the homeless, the overlooked. Keep an honest relationship with your ambition.",
                                    "es": "Alimenta a los cuervos con regularidad. Los sábados, dona a personas en los márgenes — sin hogar, ignorados. Mantén una relación honesta con tu ambición."},
                         "frequency": "Daily (crows) + every Saturday for 9 weeks"},
        "affirmation": {"en": "I want clearly, not compulsively. I ground my ambition. Enough is a place I can stand.",
                        "es": "Deseo con claridad, no por compulsión. Aterrizo mi ambición. Lo suficiente es un lugar donde puedo estar."},
        "chakras_balanced": ["third_eye", "root"],
        "why_this_works": {"en": "Rahu rules hunger and the pull toward the new. When agitated, it scatters the mind into anxious chasing. The mantra contains the static, the inversion drains the over-revved nervous system, and feeding crows is the Lal Kitab way of settling Rahu's restless charge.",
                          "es": "Rahu rige el hambre y el tirón hacia lo nuevo. Cuando se agita, dispersa la mente en una persecución ansiosa. El mantra contiene la estática, la inversión drena el sistema nervioso sobreacelerado, y alimentar cuervos es la forma de Lal Kitab de asentar la carga inquieta de Rahu."},
        "frequency_hz": 268,
    },
    "Ketu": {
        "what_it_governs": {"en": "Detachment, spirituality, focus, the past, what falls away, liberation.",
                            "es": "Desapego, espiritualidad, enfoque, el pasado, lo que se desprende, liberación."},
        "when_weak_symptoms": {"en": "Feeling lost or rootless, sudden endings, spiritual emptiness, scattered focus, things slipping away.",
                              "es": "Sentirte perdido o sin raíces, finales súbitos, vacío espiritual, foco disperso, cosas que se escapan."},
        "mantra": {"primary": "Om Sraam Sreem Sraum Sah Ketave Namaha", "sanskrit": "ॐ स्रां स्रीं स्रौं सः केतवे नमः",
                   "translit": "OM SRAAM SREEM SRAUM SAH KETAVE NAMAHA", "count": 108, "duration_minutes": 15,
                   "when": "Evening, in stillness, facing any direction"},
        "body": {"name": "Child's Pose (Balasana)", "minutes": 5,
                 "cue": "Fold forward, forehead down, arms resting. Let the back body widen. Surrender weight to the floor."},
        "breath": {"name": "Witness Breath", "pattern": "Natural breath, simply watched, no control", "rounds": 12},
        "daily_action": {"title": "Keep a dog / donate blankets",
                         "detail": {"en": "Care for a dog if you can. Donate blankets to those without shelter. Keep a small, steady spiritual practice — even five minutes daily.",
                                    "es": "Cuida de un perro si puedes. Dona mantas a quienes no tienen refugio. Mantén una práctica espiritual pequeña y constante — aunque sean cinco minutos al día."},
                         "frequency": "Daily practice + ongoing donations"},
        "affirmation": {"en": "I let go cleanly. I trust what falls away. I am rooted even as I release.",
                        "es": "Suelto con limpieza. Confío en lo que se desprende. Estoy enraizado incluso al soltar."},
        "chakras_balanced": ["crown", "root"],
        "why_this_works": {"en": "Ketu rules release and the inward turn. When unsettled, it leaves you rootless and scattered. The mantra steadies the dispersing energy, the forward fold returns you to the ground, and the quiet practice gives Ketu its proper channel — focus through surrender, not grasping.",
                          "es": "Ketu rige la liberación y el giro hacia adentro. Cuando está inquieto, te deja sin raíces y disperso. El mantra calma la energía que se dispersa, el pliegue hacia adelante te devuelve al suelo, y la práctica silenciosa le da a Ketu su canal propio — enfoque a través de la entrega, no del aferramiento."},
        "frequency_hz": 304,
    },
}


def get_planet_content(planet: str, language: str = "en") -> dict:
    """Localised content block for one planet — every piece from the same entry."""
    entry = PRACTICE_LIBRARY.get(planet)
    if not entry:
        return {}
    da = entry["daily_action"]
    return {
        "what_it_governs": _loc(entry["what_it_governs"], language),
        "when_weak_symptoms": _loc(entry["when_weak_symptoms"], language),
        "mantra": dict(entry["mantra"]),
        "body": dict(entry["body"]),
        "breath": dict(entry["breath"]),
        "daily_action": {"title": da["title"], "detail": _loc(da["detail"], language), "frequency": da["frequency"]},
        "affirmation": _loc(entry["affirmation"], language),
        "chakras_balanced": list(entry["chakras_balanced"]),
        "why_this_works": _loc(entry["why_this_works"], language),
        "frequency_hz": entry["frequency_hz"],
    }
